# Site settings
title: Acasquete notes
description: "Alex Casquete's Notes, things I never keep for myself"
url: "https://acasquete.github.io"
author:
  name: "Alex Casquete"
  email: "acasquete@outlook.com"
  url: "https://acasquete.github.io"

# Build settings
baseurl: / 
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

languages: ["en", "es"]
exclude_from_localizations: ["articles", "audio","css","docs","files","fonts","img","js","paintings","tag"]
defaultLang: en
languageNames:
  es: Spanish
  en: English